## Numpy

* Basic library used in scientific calculations
* Linear algebra, machine learning, data science
* Multi-dimensional arrays
* Fast access to multidimensional arrays
* The difference from the lists is having a fixed size.


![Title](img/numpy.png)


### Import Numpy Library

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])   # 1st-degree array, vector

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(5,)

In [6]:
a.ndim    # return the dimension of an array

1

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
print(a[0])
print(a[3])
print(a[2])

1
4
3


In [9]:
a[2] = 8

print(a)

[1 2 8 4 5]


In [10]:
b = np.array([[1,2,3,4],
              [5,6,7,8]])    #2nd-degree array

In [11]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b.ndim

2

In [13]:
b.shape    # 2nd-degree array with 2 row, 4 col.

(2, 4)

In [14]:
print(b[0,0])      
print(b[1,0])      
print(b[1,1])      #1st item of 1st row

1
5
6


In [15]:
print(b[0,0],b[1,0],b[1,1])

1 5 6


### Arrays with Special Values

In [16]:
#Zero Array


s = np.zeros((2,2))

print(s)

[[0. 0.]
 [0. 0.]]


In [17]:
s2 = np.ones((2,3))
print(s2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
s3 = np.full((3,3),8)
print(s3)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [19]:
#diagonal array

s5 = np.eye(4)

print(s5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
s7 = np.arange(0,10,1)   
print(s7)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
s8 = np.linspace(2,3,5)
print(s8)

[2.   2.25 2.5  2.75 3.  ]


In [22]:
s6 = np.random.random((5,5))      
print(s6)

[[0.50799271 0.12736658 0.97379175 0.8381693  0.16161778]
 [0.24888348 0.79924365 0.41983154 0.57458025 0.95705993]
 [0.14831629 0.92656247 0.37164554 0.14233799 0.69168197]
 [0.45275448 0.2650802  0.7979181  0.68886196 0.67813242]
 [0.59896951 0.81892883 0.68682129 0.77882312 0.80310758]]


In [23]:
#reshape

d2 = np.random.randint(5,10, size = (5,3))
print(d2)
print(d2.shape)

[[7 9 9]
 [8 9 5]
 [7 5 8]
 [7 5 5]
 [6 7 8]]
(5, 3)


In [24]:
d2.reshape(3,5)   #The original matrix and the new one must have the same number of items.

array([[7, 9, 9, 8, 9],
       [5, 7, 5, 8, 7],
       [5, 5, 6, 7, 8]])

In [25]:
d2.reshape(15,1)

array([[7],
       [9],
       [9],
       [8],
       [9],
       [5],
       [7],
       [5],
       [8],
       [7],
       [5],
       [5],
       [6],
       [7],
       [8]])

In [26]:
d2 = d2.reshape(3,5)
d2

array([[7, 9, 9, 8, 9],
       [5, 7, 5, 8, 7],
       [5, 5, 6, 7, 8]])

In [27]:
d2.max()

9

In [28]:
d2.min()

5

In [29]:
d2[::-1]

array([[5, 5, 6, 7, 8],
       [5, 7, 5, 8, 7],
       [7, 9, 9, 8, 9]])

In [30]:
d2.mean()

7.0

###  Concatenation

In [36]:
myArray = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
print(myArray)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [37]:
print(np.concatenate([myArray,myArray], axis = 0))  #vertical

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
print(np.concatenate([myArray,myArray], axis = 1)) #horizontal

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]


### Slicing

In [39]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

b = a[:2, 1:3]    

print(b)

[[2 3]
 [6 7]]


In [40]:
print(a[0,1])

2


In [41]:
b[0,0] = 77    

print(a[0,1])

77


In [42]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Aritmetic Operations

In [43]:
x = np.array([[1,2],[3,4]], dtype= np.float64)
y = np.array([[5,6],[7,8]], dtype= np.float64)


print(x+y)

print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [44]:
print(x-y)

print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [45]:
print(np.dot(x,y))  #This function returns the dot product of two arrays.

[[19. 22.]
 [43. 50.]]


### Dot Product

In [46]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

a = np.array([9,10])
b = np.array([11,12])


print(a.dot(b))

print(np.dot(a,b))

219
219


In [47]:
print(x.dot(a))

print(np.dot(a,x))

[29 67]
[39 58]


In [48]:
print(y.dot(b))

print(np.dot(y,b))

[127 173]
[127 173]


In [49]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))

print(np.sum(x, axis = 0))

print(np.sum(x, axis = 1))

10
[4 6]
[3 7]


### Transpose

In [50]:
x = np.array([[1,2],
              [3,4]])


print(x.T)

[[1 3]
 [2 4]]


In [51]:
v = np.array([[1,2,3]])


print(v.T)

[[1]
 [2]
 [3]]
